name: Read S3 Variable

on:
  push:
    branches:
      - main 

jobs:
  read-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get file from s3
        run: |
          aws s3 cp s3://demo-bucket-acs/version.json ./version.json

      - name: Read JSON Variable
        run: |
          new_version=$(jq -r '.image_version' ./version.json)
          echo "new version is: $new_version"