name: Read S3 Variable

on:
  push:
    branches:
      - main 

jobs:
  read-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: gunjanchhabra1
          password: ${{ secrets.SECRET_TOKEN }}

      - name: Get file from s3
        run: |
          aws s3 cp s3://demo-bucket-acs/version.json ./version.json

      - name: Read JSON Variable
        id: get_version
        run: |
          new_version=$(jq -r '.image_version' ./version.json)
          echo "$new_version" >> $GITHUB_OUTPUT

      - name: Build the new Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:$new_version .
          docker push ghcr.io/${{ github.repository }}:$new_version
        env:
          new_version: ${{ steps.get_version.outputs.version }}